import connection
import querys
import matplotlib.pyplot as plt
import numpy as np

cursor = connection.connection.cursor()

streamingType = querys.streamingType()
distribuitonStreaming = querys.distributionStreamings()
countryTitles = querys.countryTitles()
personActorDirector = querys.personActorDirector()
streamingRuntimeMovie = querys.streamingRuntimeMovie()
streamingRuntimeShow = querys.streamingRuntimeShow()
streamingValues = querys.streamingMostValue()
bestMovieDecade = querys.bestMovieByDecade()
bestDecade = querys.bestDecade()
distributionGenreStreaming = querys.distributionGenreStreaming()
scorePopularity = querys.scorePopularity()
scoreRuntime = querys.scoreRuntime()
scoreYear = querys.scoreYear()
correlacionScores = querys.correlacionScores()
genreScore = querys.genreScore()
genreRestriction = querys.genreRestricted()
countryShows = querys.countryShows()
countryMovies = querys.countryMovies()
streamingCountry = querys.streamingCountry()
genreYear = querys.genreYear()
typePopularity = querys.typePopularity()
genrePopularityMovie = querys.genrePopularityMovie()
genrePopularityShow = querys.genrePopularityShow()
yearPopularity = querys.yearPopularity()
runtimePopularity = querys.runtimePopularity()
yearRuntime = querys.yearRuntime()
yearStreaming = querys.yearStreaming()
probGenreScore = querys.probGenreScore()
bestDecadeMovie = querys.bestDecadeMovie()
genreScorePopularity = querys.genreScorePopularity()
genreRestricted = querys.genreRestrictedQuantity()
countryStreamingQuantity = querys.countryStreamingQuantity()
moviesShows = querys.moviesShows()

cursor.execute(distributionGenreStreaming)
results = cursor.fetchall()
